// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class CollaboratorEarning
{
    public int EarningId { get; set; }

    public int UserId { get; set; }

    public int OrderItemId { get; set; }

    public decimal EarningAmount { get; set; }

    public string Status { get; set; }

    public DateTime? PaidAt { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    public virtual OrderItem OrderItem { get; set; }

    public virtual User User { get; set; }
}