// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Costume
{
    public int CostumeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }
    public int CreatedByUserId { get; set; }
    public virtual User CreatedBy { get; set; } = null!; // 👈 BỔ SUNG DÒNG NÀY

    public int CategoryId { get; set; }

    public decimal? PriceSale { get; set; }

    public decimal? PriceRent { get; set; }

    public int Quantity { get; set; }

    public string Size { get; set; }

    public string Condition { get; set; }

    public string Gender { get; set; }

    public bool IsActive { get; set; } = true;

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    public virtual Category Category { get; set; }

    public virtual ICollection<CostumeImage> CostumeImages { get; set; } = new List<CostumeImage>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual User Owner { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}