// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int CustomerId { get; set; }

    public string Status { get; set; }

    public decimal? TotalPrice { get; set; }

    public DateTime? RentStart { get; set; }
    public DateTime? RentEnd { get; set; }

    public bool? IsPaid { get; set; }

    public string Note { get; set; }
    public string RecipientName { get; set; }
    public string RecipientPhone { get; set; }
    public string ShippingAddress { get; set; }
    public bool? HasIdentityCard { get; set; } // ✅ Thêm dòng này

    public Deposit? Deposit { get; set; }
    public ICollection<OrderStatusHistory>? StatusHistories { get; set; }
    public ReturnInspection? ReturnInspection { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    public virtual User Customer { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}