name: Deploy ASP.NET Core Web API to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore SoulFashion/SoulFashion.csproj

    - name: Build
      run: dotnet build SoulFashion/SoulFashion.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish SoulFashion/SoulFashion.csproj --configuration Release --output ./publish

    - name: Debug publish profile secret
      run: echo "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" | wc -c

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'soulfashion'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
